### PR TITLE
Added CI tools, allow to use without meta-fields

### LINKED ISSUE #4: Approval without duration
Would it be possible to add a mode where you do not have to specify the daily working times?

I am sure you have valid reasons in your use-case.
But I see many scenarios, where you want to approve / reject times without the necessity of checking daily working times.

Times change and working contracts do not require to have such a setup nowadays 😁

### PR DESCRIPTION
**Pull request by kevinpapst**
This is a huge PR, sorry for that!

It contains:
1. new CI tools
2. A new interface and service to use the bundle WITHOUT meta-fields and daily working times - fixes #4 
3. Code style and fixes

You could only use some commits if you prefer that.

First of all: I added a Github workflow to lint the entire codebase and prevent accidental code problems by using PHP-CS for code styles and phpstan for static code analysis.

I applied both tools, so big parts of the changes are "fixes".

With the changes from (2) anyone can now install the bundle and use it directly. People who want to check their working times can install the MetaField Bundle and configure the fields.

And please test it in detail, because my system has no MetaField setting for the working times. So I did not test that the refactoring did what I wanted... even though I expect that got it right .... but you never know 😁

### CODE REVIEW

**Comment by KatjaGlassConsulting** [comment]
Oh wow! Thanks a lot! I am very busy the next three weeks, but I blocked the 17th October for detailed review and testing. I expect your PR to be included in October!

**Comment by kevinpapst** [comment]
I know, I really sorry for that way too large PR... it's a burden, thanks for not closing it directly!

Have a look at the last commit, it reduced the amount of DB queries in my dev system from ... well, see these screenshots:

Before:
Bildschirmfoto 2022-09-26 um 19 43 27

After:
Bildschirmfoto 2022-09-26 um 19 43 40

It is one of these small changes with a **huge** impact...

**Review by KatjaGlassConsulting — APPROVED** [review]

**Comment by kevinpapst** [comment]
Thanks for merging 👍

**Comment by KatjaGlassConsulting** [comment]
Thanks for this excellent PR. :)

**Pull request merged**
